alumniportal/alumniportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static #
from django.conf import settings #

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('chat/',include('chat.urls')),
    path('post/', include('post.urls')),
]
if settings.DEBUG: #
   urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alumniportal/chat/urls.py
from django.urls import path,include
from . import views

urlpatterns = [
    path(r't/<room_name>/',views.chatroom,name='chatroom'),
    path(r'start/',views.start_chat),
    path(r'online/',views.get_online),
    path(r'last-active/',views.get_last_active),
    path(r'',views.chats,name='chats')
]

alumniportal/post/urls.py
from django.contrib import admin
from django.urls import path, re_path ,include
from . import views
from django.views.decorators.csrf import csrf_exempt
app_name='post'

urlpatterns=[
    path('', views.index ,name='wall'),
    path('create-post/', views.create_post ,name='create_post'),
    path('delete/<pk>/', views.delete_post ,name='post_delete'),
    path('update/<pk>/', views.update_post ,name='post_update'),
    path('detail/<pk>', views.post_details, name='post_detail'),
    path('load-feed/<index>',views.load_feed),
    path('feed/',views.feed, name='feed'),
    path('like-post/',views.like_post, name='like-post'),
    path('fileUpload/', csrf_exempt(views.upload_file_view)),
    path('feign-fileUpload/', csrf_exempt(views.feign_file_upload)),
    path('imageUpload/', csrf_exempt(views.upload_image_view)),
    path('feign-imageUpload/', csrf_exempt(views.feign_image_upload)),
    path('comment/<pk>/', views.comment, name='comment'),
    path('load-comment/<id>', views.load_comment),
]

alumniportal/post/models.py
from users.models import Account
from django.db import models
from .editorjsmod import EditorJsFieldMod
import datetime

# Create your models here.
# class Post(models.Model):
#     author=models.ForeignKey(User,on_delete=models.CASCADE,related_name='posts',null=True)
#     text=models.CharField(max_length=1000, null=True)
#     datetime=models.DateTimeField(auto_now_add=True)
#     likess=models.ManyToManyField(User,related_name='likes')
#     @property
#     def rev_priority(self):
#         age=(datetime.datetime.now()-self.datetime).total_seconds()//(3600*24)
#         likes_count=len(self.likes.all())
#         #in every 3 day group, the priority is decided by likes 
#         return age//3 + 1/(likes_count or 1)




# class Like(models.Model):
#     post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='likes')
    # author=models.CharField(max_length=50)



class Post(models.Model):
    author=models.ForeignKey(Account,on_delete=models.CASCADE,related_name='posts',null=True)
    datetime=models.DateTimeField(auto_now_add=True)
    likes=models.ManyToManyField(Account,related_name='liked_posts')
    content=EditorJsFieldMod(
        editorjs_config={
            "tools":{
                "Image":{
                    "config":{
                        "endpoints":{
                            "byFile":'http://localhost:8000/post/feign-imageUpload/',
                            "byUrl":'http://localhost:8000/post/feign-imageUpload/',
                        },
                        "additionalRequestHeaders":[{"Content-Type":'multipart/form-data'}]
                    }
                },
                "Attaches":{
                    "config":{
                        "endpoint":'http://localhost:8000/post/feign-fileUpload/'
                    }
                }
            },
            "logLevel":"ERROR"
        },null=True)
    @property
    def rev_priority(self):
        age=(datetime.datetime.now()-self.datetime).total_seconds()//(3600*24)
        likes_count=len(self.likes.all())
        #in every 3 day group, the priority is decided by likes 
        return age//3 + 1/(likes_count or 1)

class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments',null=True)
    author=models.ForeignKey(Account,on_delete=models.CASCADE,related_name='comments',null=True)
    content=models.CharField(max_length=500, null=True)
    create_date=models.DateTimeField(auto_now_add=True)

alumniportal/post/forms.py
from .models import Post, Comment
from django import forms
from django_editorjs import EditorJsField

class PostForm(forms.ModelForm):
    class Meta():
        model=Post
        fields=['content']
        labels={'content':''}

class CommentForm(forms.ModelForm):
    content= forms.CharField(label='', widget=forms.Textarea(attrs={'placeholder': ''}))
    class Meta:
        model=Comment
        fields=['content']
        labels={'content':''}

alumniportal/post/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render ,redirect, get_object_or_404
from django.urls import reverse
import requests
from django.core.files.storage import FileSystemStorage
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.views.generic.detail import DetailView
from users.models import Account
# Create your views here.

def index(request):
    return render(request,'post_create.html',{'postform':PostForm})
def create_post(request):
    if request.method=='POST':
        postform=PostForm(request.POST)
        print(request.POST)
        if postform.is_valid():
            post=postform.save(commit=False)
            post.author=request.user.account
            post.save()
            return redirect('post:feed')
        else:
            return HttpResponse('form-inv')
    else:
        return HttpResponse('Invalid')

def post_details(request, pk):
    post=Post.objects.get(pk=pk)
    return render(request,'post_create.html',{'post':post})

class PostDetailView(DetailView):
    model=Post
    context_object_name='post'

def update_post(request, pk):
    if request.method=='POST':
        form=PostForm(request.POST)
        if form.is_valid():
            post=form.save(commit=False)
            post.user=request.user
            post.save()
            obj=get_object_or_404(Post, pk=pk)
            obj.delete()
        return redirect('post:mypage')
    else:
        obj=get_object_or_404(Post, pk=pk)
        form=PostForm(instance=obj)
        context={}
        context['form']=form
        return render(request, 'alumni_response/post_update.html', context)


def delete_post(request,pk):
    if request.user.is_authenticated:
        try:
            post=Post.objects.get(pk=pk)
            post.delete()
            return HttpResponse('success')
        except Post.DoesNotExist:
            return HttpResponse('doesNotExist',status=500)
    else:
        return HttpResponse('notLoggedIn',status=500)

import json
from urllib.parse import unquote
def upload_image_view(request):
    f=request.FILES['image']
    fs=FileSystemStorage()
    filename=str(f)
    fileurl='posts/'+ request.user.username + '/'
    filepath=fs.save(fileurl + filename,f)
    fileurl=unquote(fs.url(filepath))
    return JsonResponse({'success':1,'file':{'url':fileurl,'path':filepath}})

def feign_image_upload(request):
    resp=upload_image_view(request)
    fs=FileSystemStorage()
    filename=json.loads(resp.content)['file']['path']
    print(filename)
    fs.delete(filename)
    return resp

def upload_file_view(request):
    f=request.FILES['file']
    size=int(request.POST['size'])
    fs=FileSystemStorage()
    filename=str(f)
    fileurl='posts/'+ request.user.username + '/'
    filepath=fs.save(fileurl + filename,f)
    fileurl=unquote(fs.url(filepath))
    return JsonResponse({'success':1,'file':{'url':fileurl,"size":size,"name":str(f),"extension":"ext", "path": filepath}})
    # return redirect('alumni_response:mypage')

def feign_file_upload(request):
    resp=upload_file_view(request)
    fs=FileSystemStorage()
    filename=json.loads(resp.content)['file']['path']
    fs.delete(filename)
    return resp
# class PostDetailView(DetailView):
#     model=Post
#     context_object_name='post'
import datetime
def get_feed(user):
    feed=[]
    if user.is_authenticated:
        follow_feed=[]
        following = list(user.account.following.all())
        following.append(user.account)
        for fuser in following:
            for post in fuser.posts.all():
                post_age = datetime.datetime.now()-post.datetime
                post_age = post_age.total_seconds() / 3600;
                if post_age<=24:
                    follow_feed.append(post)
        follow_feed.sort(key=lambda x: x.datetime, reverse=True)
        general_feed=list(Post.objects.all())
        general_feed.sort(key=lambda x:x.rev_priority)
        feed=follow_feed[:]
        for post in general_feed:
            if post not in follow_feed:
                feed.append(post)
    return feed


def like_post(request):
    if request.method == 'GET':
        post_id = request.GET['post_id']
        if request.user.is_authenticated:
            post=Post.objects.get(pk=post_id)
            acc=request.user.account
            if acc in post.likes.all():
                post.likes.remove(acc)
                msg="unliked"
            else:
                post.likes.add(acc)
                msg="liked"
            post.save()
            return HttpResponse(msg,status=200)
        else:
            return HttpResponse("Not Logged in!", status=500)
    else:
        return HttpResponse("unsuccessful", status=500)


from rest_framework import serializers
import json

class PostSerializer(serializers.ModelSerializer):
    id=serializers.SerializerMethodField()
    author = serializers.SerializerMethodField()
    like_count = serializers.SerializerMethodField()
    datetime=serializers.DateTimeField(format="%d %b,%Y %H:%M:%S")
    class Meta:
        model = Post
        fields = ['author','like_count','datetime','content','id']
    def get_author(self, post):
        if post.author:
            return (' ').join([ x.capitalize() for x in post.author.name.split()])
        else:
            return 'Anonymous'
    def get_like_count(self,post):
        return len(post.likes.all())
    def get_id(self,post):
        return post.pk




def load_feed(request,index):
    load_count=5
    index=int(index)
    user=request.user
    if not user.is_authenticated:
        return HttpResponse(json.dumps({'error':'Not Logged In'}),status=500)
    feed=get_feed(user)
    posts=[]
    if len(feed)>=index*load_count:
        for post in feed[index*load_count:min(len(feed),load_count*(index+1))]:
            data=PostSerializer(post).data
            data['is_liked']=user.account in post.likes.all()
            posts.append(data)
        return HttpResponse(json.dumps(posts),status=200)
    else:
        return HttpResponse(json.dumps({'error':'No more posts'}),status=500)

def feed(request):
    context={}
    context['commentform']=CommentForm
    return render(request, 'feed.html', context)



def comment(request, pk):
    if request.method=='POST':
        commentform=CommentForm(request.POST)
        post=get_object_or_404(Post, pk=pk)
        if commentform.is_valid():
            comment=commentform.save(commit=False)
            comment.post=post
            comment.author=request.user.account
            comment.save()
            return HttpResponse('success')
            # return HttpResponse(json.dumps(comment), status=200)
        else:
            return HttpResponse('form-inv', status=500)
    else:
        return HttpResponse('Invalid', status=500)


def load_comment(request, id):
  
    # comments=Comment.objects.all().filter(pk=id)
    comments=[]
    for comment in Post.objects.get(pk=id).comments.all():
        dic={}
        dic['author']=comment.author.name
        dic['create_date']=comment.create_date.strftime("%d/%m/%y")
        dic['content']=comment.content
        comments.append(dic)
    print(comments)
    return HttpResponse(json.dumps(comments), status=200)

alumniportal/post/templates/comment.html
<link rel="stylesheet" href="/static/stylesheets/style-post.css">

<div style="height: 100%; margin: 0;">
    <div class="comment-box jumbotron">
       <div>
        <button type="button" class="close modal-close ml-auto hehe" data-dismiss="modal" aria-label="Close"><span style="text-color:white;" aria-hidden="true">×</span></button>
        <br><br>
        <div id="comment-feed" class="overflow-scroll" style="height: 200px;">

        </div>
        <br><br>
        <form method="POST" id="comment-form" style="width: 350px; margin: auto; height: 100px; position: absolute; bottom: 10px; float: left;">
            {% csrf_token %}
            <div class="com" style="width: 300px; height: 100px;">
                {{commentform.content}}
                <button class="comment-form-submit" 
            style="font-size: 18px; color:white; background: rgb(67, 79, 214); border: none; padding: 5px; width: 120px;">Post</button>
        </div>
            
        </form>
       </div>
    </div>
</div>


<template id="comment-template">
    <div class='comment'>
        <div class="comment-header">
            <small class="comment-author"></small>
            <div><small class="comment-date"></small></div>
        </div>
        <div class="comment-content"></div>
</template>

alumniportal/post/templates/feed.html
{% extends "base.html" %} 
{% block style %}
<link rel="stylesheet" href="/static/stylesheets/style-post.css"> 
{% endblock %} 
{% block scripts%}
<script src="/static/scripts/post.js"></script>
{% endblock %} 

{% block content %}


<div >
    {% include 'comment.html' %}
</div>


<section id="feed">

</section>
<script type="text" id="data-username">{{user.username}}</script>
<section id="panel-right">
    <table>
        <tbody>
            <tr>
                <th>Following</th>
            </tr>
            {% for acc in user.account.following.all %}
            <tr>
                <td>{{acc.name}}</td>
            </tr>
            {% empty %}
            <tr>
                <td>None</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <table>
        <tbody>
            <tr>
                <th>Followers</th>
            </tr>
            {% for acc in user.account.followers.all %}
            <tr>
                <td>{{acc.name}}</td>
            </tr>
            {% empty %}
            <tr>
                <td>None</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <section id="online-panel" class="content">
        <span class="online-panel-header">Online</span>
        <template id="tmp-online-user">
          <div class="online-user">
            <a href="">
              <img src="/static/img/default-avatar.svg">
              <span></span>
            </a>
            <img src="/static/img/message.svg" data-self="{{user.username}}" data-other="" data-csrf="{{csrf_token}}">
          </div>
        </template>
      </section>


</section>

<template id="post-template">
    <div class='post'>
        <div class="post-header">
            <div class="post-author"></div>
            <div class="post-date"></div>
        </div>
        <div class="post-content"></div>
        <div class="post-footer">
            <div class="like-button" data-post-id="">
                    <img src="/static/like-liked.svg" alt="like-heart" class="like-img">
            </div>
            <div class="post-like-count"></div>
            <button class="comment-button" style="align: right;" >comment</button>
        </div>
    </div>
</template>


<script type="text/javascript">
    
</script>
{% endblock %}

alumniportal/post/templates/post_create.html
{% extends "base.html" %}
{% block content %}
<div id="post-form-area" style="width: 600px; margin: auto;">
    <h1>Make a Post:</h1>
    <form method="POST" action="{% url 'post:create_post' %}" id="post-form">
        {% csrf_token %}
        {{postform.media}}
        {{postform.as_p}}
        <input type="file" name="img" style="display: none;">
    </form>
    <button id="post-form-submit"
        style="font-size: 18px; color:white; background: rgb(67, 79, 214); border: none; padding: 5px; width: 120px;">Post</button>
</div>
<template>
    <div class="cdx-block image-tool image-tool--filled">
        <div class="image-tool__image">
            <div class="image-tool__image-preloader"></div>
            <img class="image-tool__image-picture">
        </div>
        <div class="cdx-input image-tool__caption" contenteditable="true" data-placeholder="Caption"></div>
        <div class="cdx-button"><svg width="20" height="20" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                <path
                    d="M3.15 13.628A7.749 7.749 0 0 0 10 17.75a7.74 7.74 0 0 0 6.305-3.242l-2.387-2.127-2.765 2.244-4.389-4.496-3.614 3.5zm-.787-2.303l4.446-4.371 4.52 4.63 2.534-2.057 3.533 2.797c.23-.734.354-1.514.354-2.324a7.75 7.75 0 1 0-15.387 1.325zM10 20C4.477 20 0 15.523 0 10S4.477 0 10 0s10 4.477 10 10-4.477 10-10 10z">
                </path>
            </svg> Select an Image</div>
    </div>
</template>

<script type="text/javascript">
    //TO PREVENT EDITORJs FROM UPLOADING FILES BEFORE ACTUAL POST
    let imgCount=0;
    $(window).on('load', function () {
        //to set the preview image
        $('[data-editorjs-wrapper=""]').bind('DOMSubtreeModified', function(){
            if($('.image-tool__image-preloader').length>imgCount){
                var bgimg=$('.image-tool__image-preloader')[imgCount].style.backgroundImage;
                if(bgimg!=''){
                    bgimg=bgimg.substring(5,bgimg.length-2);
                    if($('.image-tool__image-picture').length!=0){
                        if($('.image-tool__image-picture')[imgCount].getAttribute('src').startsWith('/media/')){
                            $('.image-tool__image-picture')[imgCount].setAttribute('src',bgimg);
                            imgCount++;
                        }
                    }
                }
                
            }
        })

        //overiding the form submit to upload the files first
        $('#post-form-submit').click(function(){
            let ctr=0,index=0;
            let editorData=JSON.parse($('#id_content').val());
            attaches.forEach(function(ele){
                console.log(ele);
                let editorData=JSON.parse($('#id_content').val());
                let fileBlocks=editorData.blocks.filter(b=>b.type=='Attaches');
                let fileUrl=fileBlocks[index].data.file.url.split('/');
                fd = new FormData();
                fd.append("file", ele,fileUrl[ fileUrl.length -1 ]);
                fd.append("size",ele.size);
                $.ajax({
                    type: "POST",
                    url:'/post/fileUpload/',
                    data: fd,
                    processData: false,
                    contentType: false,
                    success: function(data){
                        ctr++;
                        if(ctr==attaches.size+images.size){
                            console.log('done');
                            $('#post-form').submit();
                        }
                    }
                })
                index++;
            })
            index=0;
            images.forEach(function(ele){
                console.log(ele);
                let imgBlocks=editorData.blocks.filter(b=>b.type=='Image');
                let imgUrl=imgBlocks[index].data.file.url.split('/');
                fd = new FormData();
                fd.append("image", ele,imgUrl[ imgUrl.length -1 ]);
                $.ajax({
                    type: "POST",
                    url:'/post/imageUpload/',
                    data: fd,
                    processData: false,
                    contentType: false,
                    success: function(data){
                        ctr++;
                        if(ctr==attaches.size+images.size){
                            console.log('done');
                            $('#post-form').submit();
                        }
                    }
                })
                index++;
            })
        });

        let attaches=new Set();
        let images=new Set();
        let dummyFile=new Blob(['dummyFile'],{type : 'text/html'});
        //extract file from editorjs whenever it does a mock upload
        //editorjs appends a temp input to body whenever it attempts to upload
        $('body').bind('DOMSubtreeModified', function(){
            if($('body>input[type=file][accept="*"]').length>0){
                $('body>input[type=file][accept="*"]').change(function(e){
                    console.log(e.target.files);
                    attaches.add(e.target.files[0]);
                    console.log('yooo');
                })
            }
            if($('body>input[type=file][accept="image/*"]').length>0){
                $('body>input[type=file][accept="image/*"]').change(function(e){
                    console.log(e.target.files);
                    images.add(e.target.files[0]);
                    console.log('yooo');
                })
            }
        })

    })

</script>
{% endblock %}

alumniportal/post/templates/post_detail.html
<html>
    <head>
        <title></title>
    </head>
    <body>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

        <div class="container">
            <p class="text-right"><a href="{% url 'alumni_response:post_delete' post.pk %}"><small>delete</small></a> / <a
                    href="{% url 'alumni_response:post_edit' post.pk %}"><small>update</small></a></p>
            <div id="post-cont"></div>
        </div>
        <script>

            function parseHTML(data) {
                let str = ``;
                data.forEach(ele => {
                    switch (ele.type) {
                        case "paragraph":
                            str += `<p>${ele.data.text}</p>`;
                            break;
                        case "Image":
                            str += `<div style="margin: 30px 0;">
                                <img src="${ele.data.file.url}" ; style="height:400px; width:710px; object-fit:cover; display:block;">
                                <span style="font-size:15px; color:#999; font-style:italic;">${ele.data.caption}</span>
                                </div>`;
                            break;
                        case "Attaches":
                            str += `<div style="height:70px; padding:10px; background:#eee; margin:10px; width:500px;">						
                                    <img src="/static/${ele.data.file.extension}-icon.svg" style="height:50px; width:50px; float:left;" onerror="this.src = '/static/file-icon.svg';">
                                    <p style="display:block; float:left; margin: 10px 10px;">${ele.data.title}</p>
                                    <a href="${ele.data.file.url}">
                                        <img src="/static/dl-icon.svg" style="height: 50px; float:right;">
                                    </a>
                                    </div>`;
                            break;

                    }
                });
                return str;
            }
            $(document).ready(function () {
                var data = `{{post.content|safe}}`;
                data = JSON.parse(data).blocks;
                let html = parseHTML(data);
                console.log(html);
                let cont = document.getElementById("post-cont");
                cont.innerHTML = html;
            })


        </script>
    </body>
</html>